networks:
  charlymatloc.net:
    driver: bridge

services:
  api.charlymatloc:
    build:
      context: build
      dockerfile: 8.4-cli.Dockerfile
    ports:
      - "6080:80"
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - charlymatloc.net
    depends_on:
      - charlyauth.db
      - charlyoutils.db
      - charlyreserv.db
    command: "php -S 0.0.0.0:80 -t /var/php/public"
    restart: unless-stopped

  charlyfront:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./front:/usr/share/nginx/html:ro
    networks:
      - charlymatloc.net
    depends_on:
      - api.charlymatloc
    restart: unless-stopped

  charlyauth.db:
    image: "postgres:latest"
    env_file: ./charlyauthdb.env
    ports:
      - "5432:5432"
    networks:
      - charlymatloc.net
    volumes:
      - ./sql/auth:/docker-entrypoint-initdb.d
    restart: unless-stopped

  charlyoutils.db:
    image: "postgres:latest"
    env_file: ./charlyoutilsdb.env
    ports:
      - "5434:5432"
    networks:
      - charlymatloc.net
    volumes:
      - ./sql/outils:/docker-entrypoint-initdb.d
    restart: unless-stopped

  charlyreserv.db:
    image: "postgres:latest"
    env_file: ./charlyreservdb.env
    ports:
      - "5433:5432"
    networks:
      - charlymatloc.net
    volumes:
      - ./sql/reserv:/docker-entrypoint-initdb.d
    restart: unless-stopped

  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - charlymatloc.net

  composer:
    image: composer:2.8.6
    command: ["composer", "install"]
    networks:
      - charlymatloc.net
    volumes:
      - ./app:/app
    depends_on:
      - api.charlymatloc
